### ISSUE TITLE
Bunch of errors with Bevy 0.15.0.rc-3

### ISSUE THREAD

**Issue by richterk** [komadori/bevy_mod_outline#48]
Looks like you're using straight wgpu types instead of the bevy types.  I'm getting a bunch of errors trying to use space_editor (which has a dependency on your module), with the rust compiler saying it sees things like wgpu_types::Color::BLACK, when it's expecting the bevy equivalent.  Or, wgpu_types::PushConstantRange instead of bevy::bevy_render::render_resource::PushConstantRange.

**Comment by komadori** [comment]
The wgpu types are exposed directly by some of the lower-level Bevy rendering APIs. The problem is that the repository was ported to rc.2, but you're using rc.3 which requires a newer version of the wgpu-types. In any case, I've updated master to the 0.15 release and will publish a new version soon.
